name: cinecut
description: "CineCut - Professional Video Editor with AI Director, Firebase, and CineLive"
publish_to: 'none'
version: 1.1.0+2

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  webview_flutter: ^4.10.0
  webview_flutter_android: ^3.16.9
  url_launcher: ^6.3.1
  shared_preferences: ^2.3.3
  http: ^1.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
